import Head from 'next/head'
import Image from 'next/image'
//import { Inter,Quicksand,Cinzel } from '@next/font/google'
import Navbar from '@/Components/Navbar'
import Layout from '@/Components/Layout'
//import styles from '@/styles/Home.module.css'

export default function Home() {
  return (
    <>
      <Head>
        <title>Pure life Portal</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className=' bg-sky-400 min-h-screen'>
        <Navbar/>
        <Layout/>
      </div>
    </>
  )
}
